# Generated by Django 4.2.26 on 2025-11-27 01:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('volei', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='jogador',
            name='posicao_preferida',
            field=models.CharField(blank=True, choices=[('ponta', 'Ponta'), ('oposto', 'Oposto'), ('central', 'Central'), ('levantador', 'Levantador'), ('libero', 'Líbero')], max_length=20, null=True),
        ),
    ]
