# Generated by Django 4.2.26 on 2025-11-28 14:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('volei', '0002_jogador_posicao_preferida'),
    ]

    operations = [
        migrations.AddField(
            model_name='jogador',
            name='tipo_jogador',
            field=models.CharField(choices=[('fixo', 'Fixo'), ('convidado', 'Convidado')], default='fixo', max_length=20),
        ),
        migrations.AlterField(
            model_name='jogador',
            name='posicao_preferida',
            field=models.CharField(blank=True, choices=[('ponta', 'Ponta'), ('oposto', 'Oposto'), ('levantador', 'Levantador'), ('libero', 'Líbero'), ('tantofaz', 'Tanto Faz')], max_length=20, null=True),
        ),
    ]
