# Generated by Django 4.2.26 on 2025-11-28 18:58

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('volei', '0003_jogador_tipo_jogador_alter_jogador_posicao_preferida'),
    ]

    operations = [
        migrations.CreateModel(
            name='Partida',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pontos_time_a', models.IntegerField(default=0)),
                ('pontos_time_b', models.IntegerField(default=0)),
                ('start_time', models.DateTimeField(blank=True, null=True)),
                ('end_time', models.DateTimeField(blank=True, null=True)),
                ('status', models.CharField(choices=[('agendada', 'Agendada'), ('em_andamento', 'Em Andamento'), ('finalizada', 'Finalizada')], default='agendada', max_length=20)),
                ('time_a', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='partidas_como_time_a', to='volei.time')),
                ('time_b', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='partidas_como_time_b', to='volei.time')),
                ('vencedor', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='vitorias', to='volei.time')),
            ],
            options={
                'verbose_name': 'Partida',
                'verbose_name_plural': 'Partidas',
                'ordering': ['-start_time'],
            },
        ),
        migrations.CreateModel(
            name='EventoPonto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sequencia', models.IntegerField()),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('partida', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='eventos', to='volei.partida')),
                ('time', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='volei.time')),
            ],
            options={
                'verbose_name': 'Evento de Ponto',
                'verbose_name_plural': 'Eventos de Pontos',
                'ordering': ['sequencia'],
                'unique_together': {('partida', 'sequencia')},
            },
        ),
    ]
