# Generated by Django 5.0.14 on 2026-03-24 13:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('volei', '0004_partida_eventoponto'),
    ]

    operations = [
        migrations.AddField(
            model_name='jogador',
            name='data_nascimento',
            field=models.DateField(blank=True, null=True, verbose_name='Data de Nascimento'),
        ),
    ]
